version: '3.7'
services:
  db:
    image: 'mcr.microsoft.com/mssql/server:2022-preview-ubuntu-22.04'
    container_name: mt_db_srv
    restart: unless-stopped
    #command:
    #  - --disable-partition-engine-check
    ports:
      - '1433:1433'
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: 's8s!Np#m76LV#iN'
      MSSQL_PID: 'Developer'
    working_dir: /app
    volumes:
      - './volumes/mssql/data:/var/lib/mssql'
      - './volumes/mssql/init.sql:/app/init.sql'
    networks:
      - mtdev_network
  back:
    build:
      args:
        user: 'krs'
        uid: '1000'
      context: ./infra/back
      dockerfile: Dockerfile
    image: mt_app
    container_name: mt_app_back
    restart: unless-stopped
    ports:
      - "8089:8089"
    volumes:
      - './src/back:/app'
    networks:
      - mtdev_network
  front:
    build:
      context: ./infra/front
      dockerfile: Dockerfile
    image: mt_front
    container_name: mt_app_front
    restart: unless-stopped
    ports:
      - "3001:3000"
    volumes:
      - "./src/front:/app"
    networks:
      - mtdev_network
networks:
  mtdev_network:
    driver: bridge