"""Initial Migration

Revision ID: 9fa82cdf3ff3
Revises: 
Create Date: 2023-11-08 00:10:51.713878

"""
import os

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '9fa82cdf3ff3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employee',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(length=250), nullable=False),
                    sa.Column('last_name', sa.String(length=550), nullable=False),
                    sa.Column('birth_date', sa.Date(), nullable=False),
                    sa.Column('employee_number', sa.String(), nullable=False),
                    sa.Column('curp', sa.String(), nullable=False),
                    sa.Column('ssn', sa.String(), nullable=False),
                    sa.Column('phone_number', sa.String(length=10), nullable=False),
                    sa.Column('nationality', sa.String(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('beneficiary',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(length=250), nullable=False),
                    sa.Column('last_name', sa.String(length=550), nullable=False),
                    sa.Column('birth_date', sa.Date(), nullable=False),
                    sa.Column('curp', sa.String(), nullable=False),
                    sa.Column('ssn', sa.String(), nullable=False),
                    sa.Column('phone_number', sa.String(length=10), nullable=False),
                    sa.Column('nationality', sa.String(), nullable=True),
                    sa.Column('participation_percentage', sa.Integer(), nullable=True),
                    sa.Column('employee_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['employee_id'], ['employee.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###

    op.execute("""
        CREATE PROCEDURE dbo.sp_create_employee
            @name VARCHAR(250),
            @last_name VARCHAR(550),
            @birth_date DATE,
            @employee_number VARCHAR(100),
            @curp VARCHAR(30),
            @ssn VARCHAR(30),
            @phone_number VARCHAR(20),
            @nationality VARCHAR(180)
        AS
        BEGIN
            INSERT INTO employee (name, last_name, birth_date, employee_number, curp, ssn, phone_number, nationality)
            values (@name, @last_name, @birth_date, @employee_number, @curp, @ssn, @phone_number, @nationality)
            RETURN 0
        END;
    """)

    op.execute("""
        CREATE PROCEDURE dbo.sp_create_beneficiary
            @name varchar (250),
            @last_name varchar(550),
            @birth_date DATE,
            @curp varchar(30),
            @ssn varchar(30),
            @phone_number varchar(20),
            @nationality varchar(180),
            @participation_percentage int,
            @employee_id int
        AS
        BEGIN
            INSERT INTO beneficiary (name, last_name, birth_date, curp, ssn, phone_number, nationality, participation_percentage, employee_id) values (@name, @last_name, @birth_date, @curp, @ssn, @phone_number, @nationality, @participation_percentage, @employee_id)
            RETURN 0
        END;
    """)

    op.execute("""
        CREATE PROCEDURE dbo.sp_update_employee
            @employee_id int,
            @name varchar (250),
            @last_name varchar(550),
            @birth_date DATE,
            @employee_number varchar(100),
            @curp varchar(30),
            @ssn varchar(30),
            @phone_number varchar(20),
            @nationality varchar(180)
        AS
        BEGIN
            UPDATE employee SET name=@name, last_name=@last_name, birth_date=@birth_date, employee_number=@employee_number, curp=@curp, ssn=@ssn, phone_number=@phone_number, nationality=@nationality
            WHERE id = @employee_id
            RETURN 0
        END;
    """)

    op.execute("""
       CREATE PROCEDURE dbo.sp_update_beneficiary
            @beneficiary_id int,
            @name varchar (250),
            @last_name varchar(550),
            @birth_date varchar(50),
            @curp varchar(30),
            @ssn varchar(30),
            @phone_number varchar(20),
            @nationality varchar(180),
            @participation_percentage int
        AS
        BEGIN
            UPDATE beneficiary SET name=@name, last_name=@last_name, birth_date=@birth_date, curp=@curp, ssn=@ssn, phone_number=@phone_number, nationality=@nationality, participation_percentage=@participation_percentage
            WHERE id = @beneficiary_id
            RETURN 0
        END; 
    """)

    op.execute("""
        CREATE PROCEDURE dbo.sp_delete_employee(@employee_id int) AS
        BEGIN
            DELETE FROM employee
            WHERE id = @employee_id
            RETURN 0
        END;
    """)

    op.execute("""
        CREATE PROCEDURE dbo.sp_delete_beneficiary(@beneficiary_id int) AS
        BEGIN
            DELETE FROM beneficiary
            WHERE id = @beneficiary_id
            RETURN 0
        END;
    """)


def downgrade():
    connection = op.get_bind()
    op.execute("DROP PROCEDURE IF EXISTS dbo.sp_create_employee;")
    op.execute("DROP PROCEDURE IF EXISTS dbo.sp_create_beneficiary;")
    op.execute("DROP PROCEDURE IF EXISTS dbo.sp_update_employee;")
    op.execute("DROP PROCEDURE IF EXISTS dbo.sp_update_beneficiary;")
    op.execute("DROP PROCEDURE IF EXISTS dbo.sp_delete_employee;")
    op.execute("DROP PROCEDURE IF EXISTS dbo.sp_delete_beneficiary;")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('beneficiary')
    op.drop_table('employee')
    # ### end Alembic commands ##
