"""Delete Cascade behavior

Revision ID: e78015ca4a79
Revises: 9fa82cdf3ff3
Create Date: 2023-11-08 22:06:28.419118

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e78015ca4a79'
down_revision = '9fa82cdf3ff3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    #with op.batch_alter_table('beneficiary', schema=None) as batch_op:
    #    batch_op.drop_column('employee_number')

    op.create_foreign_key(
        'fk_beneficiary_employee',
        'beneficiary',
        'employee',
        ['employee_id'],
        ['id'],
        ondelete='CASCADE'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
